apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: openebs.io/provisioner-iscsi
metadata:
  name: openebs-jiva-gpd-3repl
  annotations:
    cas.openebs.io/config: |
      - name: ControllerImage
        value: openebs/jiva:0.8.1
      - name: ReplicaImage
        value: openebs/jiva:0.8.1
      - name: VolumeMonitorImage
        value: openebs/m-exporter:0.8.1
      - name: ReplicaCount
        value: "3"
      - name: StoragePool
        value: gpdpool