apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-pool-sparse-2-replicas
  labels:
    replicas: "2"
    type: "cstor"
    storage: "sparse"
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "openebs-cstor-pool-sparse"
      - name: ReplicaCount
        value: "2"
provisioner: openebs.io/provisioner-iscsi        
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-pool-sparse-1-replicas
  labels:
    replicas: "1"
    type: "cstor"
    storage: "sparse"
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "openebs-cstor-pool-sparse"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi        
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-pool-fast-2-replicas
  labels:
    replicas: "2"
    type: "cstor"
    storage: "fast"
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "openebs-cstor-pool-fast"
      - name: ReplicaCount
        value: "2"
provisioner: openebs.io/provisioner-iscsi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-pool-fast-1-replicas
  labels:
    replicas: "1"
    type: "cstor"
    storage: "fast"
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "openebs-cstor-pool-fast"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi        