apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota-demo
spec:
  hard:
    persistentvolumeclaims: "1"
    services.loadbalancers: "0"
    services.nodeports: "0"



# https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/
# String	API Object	"pods"	Pod	"services"	Service	"replicationcontrollers"	ReplicationController	"resourcequotas"	ResourceQuota	"secrets"	Secret	"configmaps"	ConfigMap	"persistentvolumeclaims"	PersistentVolumeClaim	"services.nodeports"	Service of type NodePort	"services.loadbalancers"	Service of type LoadBalancer
