kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: admin
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

# # This role binding allows "jane" to read pods in the "default" namespace.
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: developer
#   namespace: demo
# subjects:
# - kind: User
#   name: jane # Name is case sensitive
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role #this must be Role or ClusterRole
#   name: developer # this must match the name of the Role or ClusterRole you wish to bind to
#   apiGroup: rbac.authorization.k8s.io

