{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up and running stuff",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sort_desc(count(up) by (job))", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Node Load 15 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(node_load15) by (instance))",
     "legendFormat": "{{instance}} - load 15"
    }
   ]
  },
  {
   "title": "Node Load 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(node_load1) by (instance))",
     "legendFormat": "{{instance}} - load 1"
    }
   ]
  },
  {
   "title": "Node Load 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(node_load5) by (instance))",
     "legendFormat": "{{instance}} - load 5"
    }
   ]
  },
  {
   "title": "Failed pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  }
 ]
}