apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        editor: vscode
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        volumeMounts:
          - name: creds
            mountPath: "/tmp/"
            readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: stolifjset
