apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
spec:
  limits:
  - default:
      cpu: 1900m
    defaultRequest:
      cpu: 1900m
    min:
      cpu: 250m
    max:
      cpu: 4000m
    type: Container