apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins
spec:
  gateways:
    - istio-ingressgateway
  hosts:
  - 'jenkins.build.svc.cluster.local'
  http:
  - match:
    - uri:
        exact: /jenkins
    route:
    - destination:
        host:  jenkins.build.svc.cluster.local
        port:
          number: 8080
