FROM ubuntu:18.04

RUN apt update && apt install -y dnsutils iputils-ping apt-transport-https curl vim wget gnupg gnupg2 \
    && curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list \
    && apt update && apt install -y kubectl \
