apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
  - name: debugger
    image: coderpews/debugger:1.0.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "56Mi"
        cpu: "128m"
    command: ["tail", "-f", "/dev/null"]