apiVersion: v1
kind: Pod
metadata:
  name: debugger
  labels:
    app: debugger
    role: debug
spec:
  containers:
    - name: debugger
      image: coderpews/debugger:1.0.1
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
